---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bwsm_cluster_role
rules:
  - apiGroups:
      - ""
    resources:
      - BitwardenSecrets
    verbs:
      - get
      - watch
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bwsm_cluster_role_binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bwsm_cluster_role
subjects:
  - kind: ServiceAccount
    name: bwsm_sa
    namespace: shell-operator
