apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shell-operator
  name: shell-operator
  namespace: shell-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shell-operator
  template:
    metadata:
      labels:
        app: shell-operator
      spec:
        containers:
          name: bwsm-shell-operator
          image: REGISTRY/CONTAIENR_NAME:CONTAINER_VERSION
          serviceAccountName: bwsm_sa
          env:
            - name: BWS_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bwsm_sa_token
                  key: .secretAccessToken
