apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: bitwardensecrets.kopf.dev
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: kopf.dev
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    kind: BitwardenSecret
    singular: bitwardensecret
    plural: bitwardensecrets
    shortNames:
    - bws
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                secretName:
                  type: string
                organization:
                  type: string
