---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bwsm_cluster_role
rules:
  - apiGroups:
      - "bwsm.com"
    resources:
      - bitwardensecrets
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "create"
      - "update"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bwsm_cluster_role_binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bwsm_cluster_role
subjects:
  - kind: ServiceAccount
    name: {{ include "bitwarden_secrets_manager_operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
